sudo: required
dist: trusty
language: node_js
node_js:
  - "10"
before_script:
  - cp config/default.json.example config/default.json
script: npm install
cache:
  npm: true
  directories:
    - "node_modules"
